
//Código para el mapa interactivo
function bone(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/hueso2.jpg" alt="Hueso"><br><span><strong></strong></span></br><br><p class="tejido">El sistema esquelético es una estructura de soporte clave dentro del cuerpo. Los huesos tienen la capacidad única de crecer y regenerarse después de una lesión. Sin embargo, algunas lesiones o la degeneración de los tejidos no pueden recuperarse por sí solas y deben ser reparadas mediante la implantación de objetos extraños después de una lesión o enfermedad. Este proceso es invasivo y no siempre mejora la calidad de vida del paciente. Han surgido nuevas técnicas que pueden mejorar la sustitución o reparación ósea. La bioimpresión 3D emplea una impresora capaz de imprimir materiales biológicos en múltiples direcciones. La bioimpresión 3D potencialmente requiere múltiples pasos y estructuras de soporte adicionales, que pueden incluir el uso de hidrogeles para la creación de andamios.</p></br>';
    document.getElementById('info').scrollIntoView()
}
function cartilago3(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/cartilago2.jpg" alt="Cartilago"><br><span><strong></strong></span></br><br><p class="tejido">El tejido cartilaginoso humano se puede categorizar en tres tipos: cartílago hialino, cartílago elástico y fibrocartílago. Cada tipo de tejido cartilaginoso posee propiedades y funciones únicas, lo que presenta un desafío significativo para la regeneración y reparación del tejido dañado. La biónica es una disciplina en la que los humanos estudian e imitan la naturaleza. Se espera que una estrategia biónica basada en un conocimiento exhaustivo de la anatomía e histología del cartílago humano contribuya al estudio fundamental de los elementos clave de la reparación de tejidos. Además, como una tecnología de ingeniería de tejidos novedosa, la bioimpresión 3D tiene la ventaja distintiva de la construcción rápida y precisa de modelos dirigidos. Así, al seleccionar materiales, células y citoquinas adecuados, y al aprovechar la tecnología de impresión avanzada y los conceptos biónicos, se pueden realizar simultáneamente múltiples propiedades beneficiosas y lograr una mejor reparación de tejidos. Este artículo ofrece una visión general de los elementos clave involucrados en la combinación de la bioimpresión 3D y las estrategias biónicas, con un enfoque particular en los avances recientes en la imitación de diferentes tipos de tejido cartilaginoso.</p></br>';
    document.getElementById('info').scrollIntoView()
    }
function skin(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/skin2.jpg" alt="Piel"><br><span><strong></strong></span></br><br><p class="tejido">Los equivalentes de piel bioimpresa en tres dimensiones (3D) se destacan como el nuevo estándar de oro para modelos alternativos a las pruebas en animales, así como para la curación de heridas de grosor total. En esta revisión, nos enfocamos en los avances e innovaciones de la bioimpresión 3D de piel para la regeneración de la piel, en los últimos cinco años. Después de una breve introducción a la anatomía de la piel, se clasifican los métodos de bioimpresión 3D y las características notables de estudios recientes como avances en materiales, estructuras y funciones. Discutiremos varias formas de mejorar el potencial clínico de la piel bioimpresa en 3D, con tecnología de impresión de última generación y nuevos biomateriales.</p></br>';
    document.getElementById('info').scrollIntoView()
    }
function heart(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/heart.jpg" alt="Corazon"><br><span><strong></strong></span></br><br><p class="tejido">La demanda de corazones de donantes ha aumentado globalmente debido a las enfermedades cardiovasculares. Recientemente, la tecnología de bioimpresión tridimensional (3D) se ha orientado hacia la creación de construcciones cardíacas clínicamente viables para el manejo del infarto de miocardio (IM) y las complicaciones asociadas. Los avances en la bioimpresión 3D muestran promesas en la reparación del tejido cardíaco después de una lesión/infracción y ofrecen una alternativa al trasplante de órganos. Este artículo resume los principios básicos de la bioimpresión 3D y los intentos recientes de reconstruir tejido cardíaco nativo funcional adulto, con un enfoque en los desafíos actuales y las estrategias prospectivas.</p></br>';
    document.getElementById('info').scrollIntoView()
    }
function liver(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/liver.jpg" alt="Higado"><br><span><strong></strong></span></br><br><p class="tejido">Las técnicas de bioimpresión pueden usarse para la fabricación in vitro de bioestructuras complejas y funcionales. Por lo tanto, se está llevando a cabo una amplia investigación sobre el uso de varias técnicas para el desarrollo de estructuras celulares en 3D. Este artículo se centra en las técnicas de escritura directa comúnmente utilizadas para la fabricación de estructuras celulares. Se describen tres tipos diferentes de técnicas de bioimpresión: bioimpresión basada en láser, bioimpresión por chorro de tinta y bioimpresión por extrusión. Además, se hace una referencia especial al uso de las técnicas de bioimpresión para la fabricación de estructuras de modelos hepáticos en 2D y 3D y plataformas de hígado en chip. El campo de la ingeniería de tejidos hepáticos se ha desarrollado rápidamente y se puede usar una amplia gama de materiales para construir nuevas estructuras hepáticas funcionales. El enfoque en el hígado se debe a su importancia como uno de los órganos más críticos para probar nuevos fármacos, ya que está involucrado en muchos procesos metabólicos y de desintoxicación, y la toxicidad hepática es a menudo la causa del rechazo de fármacos.</p></br>';
    document.getElementById('info').scrollIntoView()
    }
function cornea(){//se genera una funacion para mostrar el contenido
    document.getElementById('info').innerHTML='<img class="imagentejido" src="Imagenes/cornea.jpg" alt="Cornea"><br><span><strong></strong></span></br><br><p class="tejido">La córnea es la capa más externa del ojo y sirve para proteger el ojo y permitir la visión al refractar la luz. La necesidad de donantes de córnea sigue siendo alta, y la demanda de una alternativa artificial continúa creciendo. La bioimpresión 3D es un método nuevo y prometedor para crear órganos y tejidos artificiales. La bioimpresión 3D ofrece la disposición espacial precisa de biomateriales y células para crear estructuras tridimensionales. Dado que la córnea es un tejido avascular, lo que la hace más atractiva para la bioimpresión 3D, podría ser uno de los primeros tejidos en hacerse completamente funcional mediante bioimpresión 3D.</p></br>';
    document.getElementById('info').scrollIntoView()
    }
             



